"""Add paper trading models

Revision ID: 1ce4abc8f58a
Revises: 0006
Create Date: 2026-04-16 00:29:14.105961

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ce4abc8f58a'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('binance_testnet_api_key', sa.String(), nullable=False),
    sa.Column('binance_testnet_secret', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('paper_trade_ledger',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bot_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False, comment='BUY or SELL'),
    sa.Column('execution_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trade_ledger_bot_id'), 'paper_trade_ledger', ['bot_id'], unique=False)
    op.alter_column('api_credentials', 'environment',
               existing_type=sa.VARCHAR(length=16),
               comment='MAINNET or TESTNET',
               existing_nullable=False)
    op.alter_column('api_credentials', 'vault_secret_id',
               existing_type=sa.UUID(),
               comment='Pointer to Supabase Vault decrypted_secrets view',
               existing_nullable=False)
    op.alter_column('backtests', 'timeframe',
               existing_type=sa.VARCHAR(length=8),
               comment='e.g. 1h, 15m, 1d',
               existing_nullable=False)
    op.alter_column('backtests', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full execution configuration (BacktestParameters)',
               existing_nullable=False)
    op.alter_column('backtests', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Scalar performance values: win_rate, max_drawdown, total_trades, etc.',
               existing_nullable=False)
    op.alter_column('backtests', 'result_file_url',
               existing_type=sa.VARCHAR(length=512),
               comment='Pointer to equity_curve JSON in Supabase Storage',
               existing_nullable=True)
    op.drop_index(op.f('ix_backtests_created_at'), table_name='backtests')
    op.alter_column('bot_state', 'bot_id',
               existing_type=sa.UUID(),
               comment='PK and FK to bots.id — enforces 1-to-1',
               existing_nullable=False)
    op.alter_column('bot_state', 'current_position',
               existing_type=sa.VARCHAR(length=8),
               comment='LONG, SHORT, or FLAT',
               existing_nullable=False,
               existing_server_default=sa.text("'FLAT'::character varying"))
    op.alter_column('bot_state', 'active_quantity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Current open position size',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('bot_state', 'average_entry_price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Average price of the current open position',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('bot_state', 'daily_realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment="Today's closed profit/loss in USDT",
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('bot_state', 'daily_unrealized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Current open position mark-to-market PnL',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('bot_state', 'last_pnl_reset_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Used to reset daily PnL at 00:00 UTC',
               existing_nullable=True)
    op.alter_column('bots', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bots', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment='User-defined bot name',
               existing_nullable=False)
    op.alter_column('bots', 'environment',
               existing_type=sa.VARCHAR(length=16),
               comment='MAINNET or TESTNET',
               existing_nullable=False)
    op.alter_column('bots', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='RUNNING, STOPPED, or PAUSED_LIMIT_REACHED',
               existing_nullable=False,
               existing_server_default=sa.text("'STOPPED'::character varying"))
    op.alter_column('bots', 'trade_quantity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Asset allocation per trade (USDT)',
               existing_nullable=True)
    op.alter_column('bots', 'daily_pnl_upper_limit',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Take-profit circuit breaker (USDT)',
               existing_nullable=True)
    op.alter_column('bots', 'daily_pnl_lower_limit',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment='Stop-loss circuit breaker (USDT)',
               existing_nullable=True)
    op.alter_column('bots', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="User's chosen strategy parameter values",
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key(None, 'bots', 'strategies', ['strategy_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('strategies', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment='e.g. RSI Divergence',
               existing_nullable=False)
    op.alter_column('strategies', 'type_code',
               existing_type=sa.VARCHAR(length=64),
               comment='e.g. RSI_DIVERGENCE — matches StrategyName enum',
               existing_nullable=False)
    op.alter_column('strategies', 'parameter_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='UI constraints: defaults, min/max ranges from xlsx',
               existing_nullable=False)
    op.drop_constraint(op.f('strategies_type_code_key'), 'strategies', type_='unique')
    op.drop_index(op.f('ix_strategies_type_code'), table_name='strategies')
    op.create_index(op.f('ix_strategies_type_code'), 'strategies', ['type_code'], unique=True)
    op.alter_column('trade_logs', 'bot_id',
               existing_type=sa.UUID(),
               comment='NULL means this was a manual trade',
               existing_nullable=True)
    op.alter_column('trade_logs', 'is_manual_trade',
               existing_type=sa.BOOLEAN(),
               comment='Default: false',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trade_logs', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment='e.g. BTCUSDT',
               existing_nullable=False)
    op.alter_column('trade_logs', 'side',
               existing_type=sa.VARCHAR(length=4),
               comment='BUY or SELL',
               existing_nullable=False)
    op.alter_column('trade_logs', 'environment',
               existing_type=sa.VARCHAR(length=16),
               comment='MAINNET or TESTNET',
               existing_nullable=False)
    op.drop_index(op.f('ix_trade_logs_executed_at'), table_name='trade_logs')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='Matches Supabase auth.users.id',
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Matches Supabase auth.users.id',
               existing_nullable=False)
    op.create_index(op.f('ix_trade_logs_executed_at'), 'trade_logs', ['executed_at'], unique=False)
    op.alter_column('trade_logs', 'environment',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='MAINNET or TESTNET',
               existing_nullable=False)
    op.alter_column('trade_logs', 'side',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='BUY or SELL',
               existing_nullable=False)
    op.alter_column('trade_logs', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='e.g. BTCUSDT',
               existing_nullable=False)
    op.alter_column('trade_logs', 'is_manual_trade',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Default: false',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trade_logs', 'bot_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL means this was a manual trade',
               existing_nullable=True)
    op.drop_index(op.f('ix_strategies_type_code'), table_name='strategies')
    op.create_index(op.f('ix_strategies_type_code'), 'strategies', ['type_code'], unique=False)
    op.create_unique_constraint(op.f('strategies_type_code_key'), 'strategies', ['type_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('strategies', 'parameter_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='UI constraints: defaults, min/max ranges from xlsx',
               existing_nullable=False)
    op.alter_column('strategies', 'type_code',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='e.g. RSI_DIVERGENCE — matches StrategyName enum',
               existing_nullable=False)
    op.alter_column('strategies', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='e.g. RSI Divergence',
               existing_nullable=False)
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.alter_column('bots', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="User's chosen strategy parameter values",
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('bots', 'daily_pnl_lower_limit',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Stop-loss circuit breaker (USDT)',
               existing_nullable=True)
    op.alter_column('bots', 'daily_pnl_upper_limit',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Take-profit circuit breaker (USDT)',
               existing_nullable=True)
    op.alter_column('bots', 'trade_quantity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Asset allocation per trade (USDT)',
               existing_nullable=True)
    op.alter_column('bots', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='RUNNING, STOPPED, or PAUSED_LIMIT_REACHED',
               existing_nullable=False,
               existing_server_default=sa.text("'STOPPED'::character varying"))
    op.alter_column('bots', 'environment',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='MAINNET or TESTNET',
               existing_nullable=False)
    op.alter_column('bots', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='User-defined bot name',
               existing_nullable=False)
    op.alter_column('bots', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bot_state', 'last_pnl_reset_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Used to reset daily PnL at 00:00 UTC',
               existing_nullable=True)
    op.alter_column('bot_state', 'daily_unrealized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Current open position mark-to-market PnL',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('bot_state', 'daily_realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment="Today's closed profit/loss in USDT",
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('bot_state', 'average_entry_price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Average price of the current open position',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('bot_state', 'active_quantity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               comment=None,
               existing_comment='Current open position size',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('bot_state', 'current_position',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='LONG, SHORT, or FLAT',
               existing_nullable=False,
               existing_server_default=sa.text("'FLAT'::character varying"))
    op.alter_column('bot_state', 'bot_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='PK and FK to bots.id — enforces 1-to-1',
               existing_nullable=False)
    op.create_index(op.f('ix_backtests_created_at'), 'backtests', ['created_at'], unique=False)
    op.alter_column('backtests', 'result_file_url',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Pointer to equity_curve JSON in Supabase Storage',
               existing_nullable=True)
    op.alter_column('backtests', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Scalar performance values: win_rate, max_drawdown, total_trades, etc.',
               existing_nullable=False)
    op.alter_column('backtests', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full execution configuration (BacktestParameters)',
               existing_nullable=False)
    op.alter_column('backtests', 'timeframe',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='e.g. 1h, 15m, 1d',
               existing_nullable=False)
    op.alter_column('api_credentials', 'vault_secret_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Pointer to Supabase Vault decrypted_secrets view',
               existing_nullable=False)
    op.alter_column('api_credentials', 'environment',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='MAINNET or TESTNET',
               existing_nullable=False)
    op.drop_index(op.f('ix_paper_trade_ledger_bot_id'), table_name='paper_trade_ledger')
    op.drop_table('paper_trade_ledger')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###