"""Add PortfolioHistoryModel

Revision ID: 9ca2a68f15ec
Revises: 1ce4abc8f58a
Create Date: 2026-04-16 04:24:05.554416

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ca2a68f15ec'
down_revision: Union[str, None] = '1ce4abc8f58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False, comment='TESTNET or MAINNET'),
    sa.Column('total_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_history_timestamp'), 'portfolio_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_portfolio_history_user_id'), 'portfolio_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_history_user_id'), table_name='portfolio_history')
    op.drop_index(op.f('ix_portfolio_history_timestamp'), table_name='portfolio_history')
    op.drop_table('portfolio_history')
    # ### end Alembic commands ###